In [2]:
import numpy as np
import cv2
import time
import imutils
from datetime import datetime

In [5]:
avg = None
video = cv2.VideoCapture(0)
xvalues = list()
motion = list()
count1 = 0
count2 = 0
l= []

def find_majority(k):
  myMap = {}
  maximum = ( '', 0 ) # (occurring element, occurrences)
  for n in k:
      if n in myMap: myMap[n] += 1
      else: myMap[n] = 1

      # Keep track of maximum on the go
      if myMap[n] > maximum[1]: maximum = (n,myMap[n])

  return maximum

while 1:
  ret, frame = video.read()
  flag = True
  text=""

  frame = imutils.resize(frame, width=500)
  gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
  gray = cv2.GaussianBlur(gray, (21, 21), 0)

  if avg is None:
      print("[INFO] starting background model...")
      avg = gray.copy().astype("float")
      continue

  cv2.accumulateWeighted(gray, avg, 0.5)
  frameDelta = cv2.absdiff(gray, cv2.convertScaleAbs(avg))
  thresh = cv2.threshold(frameDelta, 5, 255, cv2.THRESH_BINARY)[1]
  thresh = cv2.dilate(thresh, None, iterations=2)
  ( cnts,_) = cv2.findContours(thresh.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

  for c in cnts:
      if cv2.contourArea(c) < 5000:
          continue
      (x, y, w, h) = cv2.boundingRect(c)
      xvalues.append(x)
      cv2.rectangle(frame, (x, y), (x + w, y + h), (0, 0, 255), 2)
      flag = False

  no_x = len(xvalues)

  if (no_x > 2):
      difference = xvalues[no_x - 1] - xvalues[no_x - 2]
      if(difference > 0):
          motion.append(1)
      else:
          motion.append(0)
            
  if flag is True:
      if (no_x > 5):
          val, times = find_majority(motion)
          if val == 1 and times >= 15:
              time = datetime.now()
              l.append(datetime.time(time))
              count1 += 1
          else:
              count2 += 1

      xvalues = list()
      motion = list()

  cv2.line(frame, (260, 0), (260,480), (0,255,0), 2)
  cv2.line(frame, (420, 0), (420,480), (0,255,0), 2)
  cv2.putText(frame, "Out: {}".format(count1), (10, 20), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 2)
  cv2.putText(frame, "T: {}".format(time), (10, 40), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 2)
  #cv2.putText(frame, "Time: {}".format(count2), (10, 40), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 2)
  cv2.imshow("Frame",frame)
  cv2.imshow("Gray",gray)
  cv2.imshow("FrameDelta",frameDelta)  
  key = cv2.waitKey(1) & 0xFF
  if key == ord('q'):
      break

video.release()
cv2.destroyAllWindows()

[INFO] starting background model...

In [6]:
print(l)

[datetime.time(10, 4, 9, 878652), datetime.time(10, 4, 40, 209390), datetime.time(10, 5, 6, 248347), datetime.time(10, 5, 19, 427131), datetime.time(10, 5, 32, 675068), datetime.time(10, 5, 48, 379383), datetime.time(10, 5, 57, 77985), datetime.time(10, 6, 12, 22631), datetime.time(10, 6, 30, 886771), datetime.time(10, 6, 49, 528783), datetime.time(10, 7, 12, 419898), datetime.time(10, 7, 32, 592152), datetime.time(10, 7, 42, 146688), datetime.time(10, 7, 58, 45624), datetime.time(10, 8, 28, 404724), datetime.time(10, 8, 41, 475260), datetime.time(10, 8, 58, 857869), datetime.time(10, 9, 20, 178847), datetime.time(10, 9, 25, 691743), datetime.time(10, 9, 56, 549085), datetime.time(10, 10, 17, 491860), datetime.time(10, 10, 28, 659611), datetime.time(10, 11, 20, 378286), datetime.time(10, 11, 46, 104138), datetime.time(10, 12, 12, 840359), datetime.time(10, 12, 50, 63787), datetime.time(10, 13, 16, 862293), datetime.time(10, 13, 49, 766956), datetime.time(10, 13, 53, 480029), datetime.time(10, 14, 23, 621026), datetime.time(10, 14, 31, 878649), datetime.time(10, 15, 16, 75392), datetime.time(10, 15, 36, 740501), datetime.time(10, 15, 44, 854409), datetime.time(10, 16, 21, 914039), datetime.time(10, 16, 44, 956516), datetime.time(10, 17, 7, 123530), datetime.time(10, 17, 25, 926467), datetime.time(10, 17, 44, 948926), datetime.time(10, 17, 50, 986868), datetime.time(10, 17, 52, 659766)]

In [7]:
print(count1)

41

In [8]:
u=0
for i in l:
    u+=1
    print ("Customer ID:",u, "      Arrival Time :",i)

Customer ID: 1       Arrival Time : 10:04:09.878652
Customer ID: 2       Arrival Time : 10:04:40.209390
Customer ID: 3       Arrival Time : 10:05:06.248347
Customer ID: 4       Arrival Time : 10:05:19.427131
Customer ID: 5       Arrival Time : 10:05:32.675068
Customer ID: 6       Arrival Time : 10:05:48.379383
Customer ID: 7       Arrival Time : 10:05:57.077985
Customer ID: 8       Arrival Time : 10:06:12.022631
Customer ID: 9       Arrival Time : 10:06:30.886771
Customer ID: 10       Arrival Time : 10:06:49.528783
Customer ID: 11       Arrival Time : 10:07:12.419898
Customer ID: 12       Arrival Time : 10:07:32.592152
Customer ID: 13       Arrival Time : 10:07:42.146688
Customer ID: 14       Arrival Time : 10:07:58.045624
Customer ID: 15       Arrival Time : 10:08:28.404724
Customer ID: 16       Arrival Time : 10:08:41.475260
Customer ID: 17       Arrival Time : 10:08:58.857869
Customer ID: 18       Arrival Time : 10:09:20.178847
Customer ID: 19       Arrival Time : 10:09:25.691743
Customer ID: 20       Arrival Time : 10:09:56.549085
Customer ID: 21       Arrival Time : 10:10:17.491860
Customer ID: 22       Arrival Time : 10:10:28.659611
Customer ID: 23       Arrival Time : 10:11:20.378286
Customer ID: 24       Arrival Time : 10:11:46.104138
Customer ID: 25       Arrival Time : 10:12:12.840359
Customer ID: 26       Arrival Time : 10:12:50.063787
Customer ID: 27       Arrival Time : 10:13:16.862293
Customer ID: 28       Arrival Time : 10:13:49.766956
Customer ID: 29       Arrival Time : 10:13:53.480029
Customer ID: 30       Arrival Time : 10:14:23.621026
Customer ID: 31       Arrival Time : 10:14:31.878649
Customer ID: 32       Arrival Time : 10:15:16.075392
Customer ID: 33       Arrival Time : 10:15:36.740501
Customer ID: 34       Arrival Time : 10:15:44.854409
Customer ID: 35       Arrival Time : 10:16:21.914039
Customer ID: 36       Arrival Time : 10:16:44.956516
Customer ID: 37       Arrival Time : 10:17:07.123530
Customer ID: 38       Arrival Time : 10:17:25.926467
Customer ID: 39       Arrival Time : 10:17:44.948926
Customer ID: 40       Arrival Time : 10:17:50.986868
Customer ID: 41       Arrival Time : 10:17:52.659766

In [73]:
b

In [10]:
import pandas as pd

In [11]:
u=1
f = []
for i in l:
    f.append({'Customer ID': u, 'Arrival Time': i })
    u+=1
d=pd.DataFrame(f)

In [12]:
d

       Arrival Time  Customer ID
0   10:04:09.878652            1
1   10:04:40.209390            2
2   10:05:06.248347            3
3   10:05:19.427131            4
4   10:05:32.675068            5
5   10:05:48.379383            6
6   10:05:57.077985            7
7   10:06:12.022631            8
8   10:06:30.886771            9
9   10:06:49.528783           10
10  10:07:12.419898           11
11  10:07:32.592152           12
12  10:07:42.146688           13
13  10:07:58.045624           14
14  10:08:28.404724           15
15  10:08:41.475260           16
16  10:08:58.857869           17
17  10:09:20.178847           18
18  10:09:25.691743           19
19  10:09:56.549085           20
20  10:10:17.491860           21
21  10:10:28.659611           22
22  10:11:20.378286           23
23  10:11:46.104138           24
24  10:12:12.840359           25
25  10:12:50.063787           26
26  10:13:16.862293           27
27  10:13:49.766956           28
28  10:13:53.480029           29
29  10:14:23.621026           30
30  10:14:31.878649           31
31  10:15:16.075392           32
32  10:15:36.740501           33
33  10:15:44.854409           34
34  10:16:21.914039           35
35  10:16:44.956516           36
36  10:17:07.123530           37
37  10:17:25.926467           38
38  10:17:44.948926           39
39  10:17:50.986868           40
40  10:17:52.659766           41

In [13]:
d.to_csv('file.csv',sep='\t',encoding='utf-8',index=False)